name = "task-management-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "task-management-db"
database_id = "34b7b706-edc5-4c52-8986-1e0e49c051a0"
